plus3it/spel

README.md
spel/minimal-linux.json
spel/scripts/amigen6-build.sh

* Add parameters `spel_customreporpm` and `spel_customreponame`
* If both custom parameters are defined, pass them to `ChrootBuild.sh`
A custom release RPM can be used by AMIGen to define a set of yum
repos to use instead of the built-in vendor repos. This allows
AMIGen to work even in environments without an Internet connection.

Use custom 'release' rpm if specified

---

README.md
spel/minimal-linux.json
spel/scripts/amigen6-build.sh

The `extras` capability takes a list of package names or group
names to be installed by yum in the chroot.

Supports the `extras` capability in amigen chrootbuild.sh

---

spel/scripts/amigen6-build.sh
spel/scripts/amigen7-build.sh

The prior method of using ssh-keyscan did not work with a fips-
enabled system. This method disables the strict host check for
the target ssh git remote.
Fixes #44

Adds ssh known_host by disabling strict host check

---

spel/scripts/amigen7-build.sh

- adjusts builds for Azure to account for changes in AMIgen7's approach to setting GRUB_CMDLINE_LINUX values in /etc/default/grub

azure adjustment to account for amigen7 updates to grubcmdline

---

spel/scripts/amigen7-build.sh

* (As titled)
New PR Alert to: @plus3it/spel

Uses cloudprovider env rather than spel_ prefixed env

---

spel/minimal-linux.json
spel/scripts/amigen6-build.sh
spel/scripts/amigen7-build.sh

When retrieving the files from s3 via the console, it automatically
applies the .txt extension, so this just acknowledges and aligns
the extension to minimize work when merging the manifests for a
release.

Uses the .txt extension for manifest files

---

docs/FAQ.md
docs/LargerThanDefaultRootEBS_EL6.md
docs/LargerThanDefaultRootEBS_EL7.md

Entries only cover AWS and expectation that growth is at launch-time (rather than lifecycle)

Add FAQs for growing disk hosting root volume-group

---

spel/kickstarts/ks.centos6.minimal.cfg

Fixes #154 .
- Partition sizes in Vagrant boxes have been increased 
-This is so the Vagrant box partition sizes more closely resemble those used in the AMIs 
- Fixes out of space erros when Builds that are successful in an AMI run out of space on the Vagrant box

Fixes #154 Partition sizes smaller on AMIs

---

tests/test_ami.py

Fixes # N/A
- check `/var/run` is a symlink to `/run` on el7

adds test to validate /var/run symlink on el7

---

spel/scripts/amigen7-build.sh
tests/test_ami.py

The python3.6 rpm from epel is not currently installing the python3 symlink.

Ensures python3 symlink exists when python3 is installed

---

spel/scripts/amigen7-build.sh

Had a bit of feedback to address on the prior patch...

Avoids overwriting python3 symlink if already installed by rpm

---

.gitlab-ci.yml
Makefile
build/build.sh
build/install.sh
build/post_build.sh
build/pre_build.sh
buildspec.yml

All of the build logic was previously built into buildspec.yml, which is specific to CodeBuild. Pulling the logic out of that into its own Makefile and a series of bash scripts allows for any CI system to be used.

Add Makefile, revamp buildpsec to use Make/bash scripts, and add gitlab-ci.yml

---

spel/scripts/amigen7-build.sh

Prior regex fails to install some packages from the Lx-GetAMI-Utils project. This modification ensures that all relevant packages from the Lx-GetAMI-Utils project are installed.
Note: issue discovered while testing the AMZN Linux 2 (20190612) updates for the Lx-GetAMI-Utils project.

Fix Amazon RPM Regex

---

tests/requirements.txt

`pytest` >=5 is not compatible with the current test setup
Reverts plus3it/spel#314

Revert "Bump pytest from 4.6.3 to 5.0.1"

---

spel/minimal-linux.json

Appears to be unable to write the AWS utils when the memory-based root-copy is sized from a `*.large` rather than a `*.xlarge`

AWS Utils might have gotten too big

---

spel/minimal-linux.json

Prevents errors related to trying to install a deprecated package.
Note: issue not previously noticed in testing because the testing-environment explicitly overrides the value of `spel_extrarpms`

Fix python 3.x RPM install

---

spel/minimal-linux.json
spel/scripts/amigen7-build.sh

Closes #380 
Validated using activators for `-g core` and `-m /path/to/GnomeDesktop.pkgs`. 
**Note:** Experienced failures with `-g <NOT_CORE>`. However, the failure is not due to issues within spel. The issues will need to addressed in AMIgen7 (see plus3it/AMIgen7#87), directly.

Add support for AMIgen7's -g and -m Flagged-options

---

Makefile

Was running into an issue with codebuild, where it cannot remove an
env in an override. So it was impossible to unset the env. By changing
the test to explicitly require a "true" value, it is easy to toggle
this option by setting any other value.

Updates test for the awscli pin to look for "true"

---

README.md

- In my last PR, I added some links to Packer's OpenStack documentation.  Unfortunately, I did some copy/pasting and didn't clean up properly, so the links were broken, and there were some unintended bullets added to the tail of the README.md.  This PR fixes that.  Sorry about that!

Fix broken references in README.md

---

.github/dependabot.yml
Dockerfile
Makefile
build/install.sh

With this patch, when hashicorp publishes a new packer version to dockerhub, dependabot will open a pr to update the Dockerfile. Mergify will then comment to kick off a build, and our github-codebuild integration will post the success/failed status back to the pr.
This is intentionally using a backrev version of packer in the Dockerfile, 1.6.5, so we'll see this in action the day after it is merged.

Uses dependabot/mergify to auto-update and test new packer versions

---

README.md

- Adding the links for us-gov-east-1.  verified the images are present.   us-gov-east-1 itself has been avail since 2018 per notice.  https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-the-new-aws-govcloud-us-east-region/

Update README.md to include us-gov-east-1 rhel-7 images

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Vagrant box was built, but no changes in the package manifest... Centos7 also had minimal changes, just the aws-cli version.

Releases spel 2021.07.1

---

README.md

It was decided to add this note to provide clarity for GovCloud users that might experience unexpected version-number differences between what's found in this project's manifest files and what might actually appear in an AMI generated in the GovCloud region for the same AMI release-ID (as originally reported in #621).
Closes #623

Add Note About Possible (CONUS) commercial vs GovCloud Regions' Version-Deltas

---

spel/scripts/amigen9-build.sh
spel/scripts/builder-prep-9.sh
tests/minimal-linux.pkr.hcl

Updates the `spel/scripts/amigen9-build.sh` and `spel/scripts/builder-prep-9.sh` files:
* Ensure that repo-references are correct: Change `ol9_UEKR6` to `ol9_UEKR7`
* Ensure that `SPEL_BUILDDEPS` variable _also_ contains the `dosfstools` and `python3-pip` RPMs

Update automation-content to account for deltas in (vendor-furnished) OL9 bootstrap images

---

spel/scripts/amigen9-build.sh
spel/scripts/builder-prep-9.sh
tests/minimal-linux.pkr.hcl

1. Updates `spel/scripts/amigen9-build.sh` and `spel/scripts/builder-prep-9.sh` to reflect correct, default repo-names.
1. Adds/corrects builder test-definitions

Update automation-content to account for deltas in (vendor-furnished) CentOS 9 Stream bootstrap images

---

spel/scripts/free-root.sh

Ensures that `fuser -vmk` is only run if `/oldroot`  is _actually_ a mounted filesystem.

Tweak `free-root.sh` script

---

spel/minimal-linux.pkr.hcl

Closes #680
Validated that proposed change allows OL9 to work while continuing to allowi OL8 (and presumably RHEL8 and COS8)  and CO7 (and presumably RHEL7) to work.

Prevent Curve 25519 from being attempted for SSH comms

---

spel/scripts/amigen8-build.sh

Fixes #740 (for EL8, only)
Adds branch-logic  to the `spel/scripts/amigen8-build.sh` script to allow avoiding execution of code-segment that breaks builds for Azure

Add logic to make things less AWS-only
