spel/scripts/amigen6-build.sh

* Adds support for specifying the URI to the 'source' repos as an ssh connection string, of the form "user@host:team/project.git". Will retrieve the ssh key for the `host` and add it to ~/.ssh/known_hosts.
Note: If the repo is private, use ssh-agent forwarding to pass in the necessary deploy key.

Add support for ssh connections to git repos

---

README.md
spel/minimal-linux.json
spel/scripts/amigen6-build.sh

Support auto-growing an LVM-enabled root volume

---

README.md
spel/minimal-linux.json

Fixes #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plus3it/spel/17)

Adds support for non-default VPCs and Subnets

---

spel/scripts/amigen6-build.sh

Fixes #16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plus3it/spel/18)

Changes git-host test to properly detect ssh-based hosts

---

spel/scripts/retry.sh
spel/scripts/vagrant.sh
spel/scripts/virtualbox.sh
spel/scripts/vmware.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plus3it/spel/21)

Lints scripts using shellcheck

---

spel/minimal-linux.json

Creates a post-processor chain for vagrant boxes

---

spel/scripts/amigen6-build.sh
spel/scripts/amigen7-build.sh

Includes the aws cli version in the AMI manifest

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/issue_template.md
README.md
docs/CONTRIBUTING.md
docs/FAQ.md

With the recent spate of issue-opens, probably good to add some more project-documentation.

Doc updates

---

README.md

Updated links to AMIs to point to public images

---

README.md

Fixed GovCloud links and RHEL 6.9 links

---

spel/kickstarts/ks.centos7.minimal.cfg
spel/minimal-linux.json
spel/scripts/base.sh
spel/scripts/cleanup.sh
spel/scripts/virtualbox.sh

Proof: https://app.vagrantup.com/lorengordon/boxes/spel-minimal-centos-7
Fixes #87

Adds a builder that creates a centos7 vagrant box (virtualbox)

---

README.md
spel/minimal-linux.json

Adds default username to readme and image description

---

spel/scripts/amigen7-build.sh
tests/requirements.txt

Depends on https://github.com/plus3it/AMIgen7/pull/58

Runs amigen7 scripts in unoffical bash strict mode "-eu -o pipefail"

---

spel/scripts/amigen7-build.sh

Installs amigen customization options into builder box

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Prepares 2018.11.2 release

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt
spel/scripts/amigen7-build.sh
tests/test_ami.py

Releases spel version 2018.11.2

---

.gitlab-ci.yml
Makefile
build/build.sh
build/install.sh
build/pre_build.sh

Current gitlabci build only allows for the commercial partition to be
built out.
Fixes # .
- 
- 
- 

Add govcloud build job

---

.gitignore
build/vagrant/Makefile
build/vagrant/README.md
build/vagrant/buildspec-vagrant.yml
build/vagrant/infra/main.tf
build/vagrant/infra/outputs.tf
build/vagrant/infra/policy/ec2_s3_access_role.json
build/vagrant/infra/policy/s3_upload_policy.json
build/vagrant/infra/userdata.sh
build/vagrant/infra/variables.tf
build/vagrant/vagrant_test.go

Fixes # .
- Automatically build vagrant box for spel

Build vagrant box for spel

---

.travis.yml

Prepares for making master the default branch

---

spel/minimal-linux.json

Enables ena and sriov attributes in AMIs

---

README.md

Adds Pull Reminders badge

---

spel/kickstarts/ks.centos7.minimal.cfg

Fixes # .
- Resize boot partition to 512MiB

Resize boot partition to 512MiB

---

CHANGELOG.md

This month's AMI introduced several new RPMs not previously captured in the initial CHANGELOG file

Add missing details to CHANGELOG file

---

docs/FAQ.md

Update FAQ to provide release-support information

---

tests/requirements.txt

Revert "Bump pytest from 4.6.3 to 5.0.1"

---

manifests/spel-minimal-centos-7-virtualbox.manifest.txt

Forgot to update the virtualbox manifest file

---

tests/test_ami.py

Add test-block for utility RPMs' associated systemd units

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-centos-7-virtualbox.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Prepares 2019.10.1 release

---

README.md
spel/minimal-linux.json

Update spel builder-specs to allow specification of alternate branch in a targeted (AMIgen7) repository.

Expose git branch

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Prepares version 2020.01.1

---

README.md
spel/minimal-linux.json
spel/scripts/amigen7-build.sh

Closes #360 
Makes use of features added to [AMIgen7](https://github.com/plus3it/AMIgen7/) via plus3it/AMIgen7#81

Adds Support for Custom root-VG layout

---

Makefile
build/build.sh
build/pre_build.sh

Need to be able to specify branch if we're allowing specification of fork

Pass var for fork/branch through

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-centos-7-virtualbox.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Releases version 20201.06.1

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-centos-7-virtualbox.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Releases version 2020.07.1

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Fixes # .
- Version change from 2020.08 to 2020.09
- 
- 

Releases version 2020.09.1

---

.mergify.yml
.travis.yml

Quick patch to fix why mergify did not comment on the other dependabot pr...

Restricts travis to master branch or pull request, adjusts mergify

---

spel/scripts/amigen7-build.sh

- Turned the actions performed as part of creating the manifest file into a function to mirror the changes made within the amigen8-build script
- moved the variable declarations to all bunched together at the top to make it easier to read and mirror amigen8-build
- 

Collect Manifest Function

---

spel/scripts/amigen7-build.sh

Enabling logging using the error handler function that was added to mirror the error handling from the amigen8 script

Add error handler references

---

spel/scripts/amigen7-build.sh

- Created function ComposeCliOptionString
- ComposeAWSutilsString
- Cosmetic changes and formatting

Created ComposeAWSutilsString to organize steps 

---

spel/scripts/amigen7-build.sh

- Changing variable for chroot to match between scripts
- adding variable to handle boot volume size like amigen8
- 

Making Chroot variable and BootSize match amigen8

---

spel/minimal-linux.json

Fixes # .
- Update minimal-linux.json with azure_vm_size": "Standard_DS3_v2"
- 
- 

Update minimal-linux.json with azure_vm_size": "Standard_DS3_v2"

---

spel/minimal-linux.json

Updated to DS5_v2 for image size
Fixes # .  to DS5_v2
- 
- 
- 

Update minimal-linux.json to DS5_v2

---

spel/minimal-linux.json
spel/scripts/amigen7-build.sh

- updating references to VGNAME variable to AMIGENVGNAME to bring amigen7 in line with amigen8
- 
- 

Changing VGNAME to AMIGENVGNAME

---

.bumpversion.cfg
CHANGELOG.md
manifests/spel-minimal-centos-7-hvm.manifest.txt
manifests/spel-minimal-centos-7-virtualbox.manifest.txt
manifests/spel-minimal-rhel-7-hvm.manifest.txt

Changes: https://github.com/plus3it/spel/compare/2021.08.1...lorengordon:2021.09.1

Bump version: 2021.08.1 → 2021.09.1

---

README.md

Corrects azure and openstack usage in readme

---

tests/minimal-linux.pkr.hcl

Make sudo request an unconfined role

---

README.md

Updates readme with new owner Account IDs

---

docs/FAQ.md
docs/OpenSSHandFIPS_EL8.md

Address:
* Compatible (EL) versions statements
* OpenSSH authentication-keys on EL8 needs

Documentation Updates

---

.editorconfig
spel/scripts/pivot-root.sh

Adds logic to account for filesystems mounted at/under `/boot`

---

spel/minimal-linux.pkr.hcl
spel/scripts/free-root.sh
spel/scripts/pivot-root.sh

Add EL9-specific Logic for Releasing the Boot-Disk

---

tests/minimal-linux.pkr.hcl
tests/scripts/grow_check.sh

Update test-launch EC2 to a UEFI-supporting instance-type
Closes #661

Change to UEFI-supporting instance-type

---

spel/scripts/free-root.sh

Make stopping of auditd service conditional

---

README.md

Closes #639
Also updates README to reference EL9 distros and EFI-boot

Adds a "lifecycle"  section to README with notes about RHEL licensing and billing on AWS 

---

build/pre_build.sh
build/vagrant/Makefile
build/vagrant/build-spel-vagrant.pkr.hcl
build/vagrant/build-spel-vagrant.sh
build/vagrant/buildspec-vagrant.yml
buildspec.yml
spel/minimal-linux.pkr.hcl

Updates build to support external packer plugins initialization

---

.github/workflows/build.yml

Updates the GitHub workflows' builder-lists to include Alma and Rocky Linux 9

Add Alma and Rocky 9 to workflows
